#ifndef TENSORFLOW_LITE_MICRO_EXAMPLES_ML_ON_RISC_SENSOR_HANDLER_H_
#define TENSORFLOW_LITE_MICRO_EXAMPLES_ML_ON_RISC_SENSOR_HANDLER_H_

#include <stdio.h>

#define FEATURE_SIZE 1024

bool read_sample_from_uart(float* buffer);

#endif  // TENSORFLOW_LITE_MICRO_EXAMPLES_ML_ON_RISC_SENSOR_HANDLER_H_